In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
import sys
import os

sys.path.insert(0, os.path.abspath("C:/Users/pc/Desktop/Week 5_6/fraud-detection/src/"))

In [4]:
from src.data_loader import load_data
from src.model import *


print('Functions imported successfully!')
print()

Functions imported successfully!

## Load Credit card processed data

In [7]:
df = load_data('C:/Users/pc/Desktop/Week 5_6/fraud-detection/data/processed/creditcard_processed.csv')
df.head()

,time,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v21,v22,v23,v24,v25,v26,v27,v28,amount,class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

### 1.	Data Preparation

In [8]:
# Separate features and target
X, y = separate_features_target(df, target_column="class")

In [9]:
# Stratified train-test split
X_train, X_test, y_train, y_test = stratified_split(
    X,
    y,
    test_size=0.2
)

In [10]:
print("Training Shape:", X_train.shape)
print("Testing Shape :", X_test.shape)

print("\nTarget Distribution (Original):")
print(y.value_counts(normalize=True))

print("\nTarget Distribution (Train):")
print(y_train.value_counts(normalize=True))

print("\nTarget Distribution (Test):")
print(y_test.value_counts(normalize=True))

Training Shape: (227845, 30)
Testing Shape : (56962, 30)

Target Distribution (Original):
class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

Target Distribution (Train):
class
0    0.998271
1    0.001729
Name: proportion, dtype: float64

Target Distribution (Test):
class
0    0.99828
1    0.00172
Name: proportion, dtype: float64

In [9]:
model, results = run_logistic_regression_pipeline(
    X_train, X_test, y_train, y_test
)

c:\Users\pc\Desktop\week 5_6\fraud-detection\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

================ MODEL EVALUATION ================

AUC-PR Score (Average Precision): 0.7427
F1 Score                       : 0.7889

Confusion Matrix:
[[56853    11]
 [   27    71]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.87      0.72      0.79        98

    accuracy                           1.00     56962
   macro avg       0.93      0.86      0.89     56962
weighted avg       1.00      1.00      1.00     56962

In [10]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 5, 10]
}

In [11]:
model, best_params, results = run_random_forest_pipeline(
    X_train, X_test, y_train, y_test,
    param_grid
)

Starting Grid Search...
Fitting 5 folds for each of 9 candidates, totalling 45 fits

In [11]:
results = run_stratified_kfold_pipeline(X, y, n_splits=5)

Fold 1 → AUC-PR: 0.8146, F1: 0.8352
Fold 2 → AUC-PR: 0.8856, F1: 0.8715
Fold 3 → AUC-PR: 0.8589, F1: 0.8840
Fold 4 → AUC-PR: 0.8450, F1: 0.8588
Fold 5 → AUC-PR: 0.8223, F1: 0.8444

========== CROSS-VALIDATION SUMMARY ==========

AUC-PR → Mean: 0.8453, Std: 0.0256
F1     → Mean: 0.8588, Std: 0.0177

## Load Fraud Data set

In [12]:
df1 = load_data('C:/Users/pc/Desktop/Week 5_6/fraud-detection/data/processed/Fraud_Data_processed.csv')
df1.head()

,signup_time,purchase_time,purchase_value,device_id,age,ip_address,class,ip_address_int,txn_count_1d,txn_velocity_1d,...,hour_of_day,day_of_week,time_since_signup,source_direct,source_seo,browser_firefox,browser_ie,browser_opera,browser_safari,sex_m
0,2015-01-11 03:47:13,2015-02-21 10:03:37,54,FGBQNDNBETFJJ,25,8.802175e+08,0,NaN,1.0,54.0,...,10,5,990.273333,False,True,False,False,False,False,False
1,2015-06-02 16:40:57,2015-09-26 21:32:16,41,MKFUIVOHLJBYN,38,2.785906e+09,0,NaN,1.0,41.0,...,21,5,2788.855278,True,False,False,False,False,True,False
2,2015-05-28 07:53:06,2015-08-13 11:53:07,47,SCQGQALXBUQZJ,25,3.560567e+08,0,NaN,1.0,47.0,...,11,3,1852.000278,False,True,False,False,False,False,True
3,2015-05-16 15:58:32,2015-05-20 23:06:42,62,IEZOHXPZBIRTE,21,7.591047e+08,0,NaN,1.0,62.0,...,23,2,103.136111,False,True,True,False,False,False,True
4,2015-01-10 06:25:12,2015-03-04 20:56:37,35,MSNWCFEHKTIOY,19,2.985180e+09,0,NaN,1.0,35.0,...,20,2,1286.523611,False,False,False,False,False,True,True

### 1. Fraud Data preparation

In [13]:
# Separate features and target
X1, y1 = separate_features_target(df1, target_column="class")

In [14]:
# Stratified train-test split
X_train_1, X_test_1, y_train_1, y_test_1 = stratified_split(
    X1,
    y1,
    test_size=0.2
)

In [15]:
print("Training Shape:", X_train_1.shape)
print("Testing Shape :", X_test_1.shape)

print("\nTarget Distribution (Original):")
print(y1.value_counts(normalize=True))

print("\nTarget Distribution (Train):")
print(y_train_1.value_counts(normalize=True))

print("\nTarget Distribution (Test):")
print(y_test_1.value_counts(normalize=True))

Training Shape: (120889, 23)
Testing Shape : (30223, 23)

Target Distribution (Original):
class
0    0.906354
1    0.093646
Name: proportion, dtype: float64

Target Distribution (Train):
class
0    0.906352
1    0.093648
Name: proportion, dtype: float64

Target Distribution (Test):
class
0    0.906363
1    0.093637
Name: proportion, dtype: float64

### 2.	Build Fraud Baseline Model

In [17]:
model1, results1 = run_logistic_regression_pipeline(
    X_train_1, X_test_1, y_train_1, y_test_1
)

ValueError: could not convert string to float: '2015-07-30 15:35:29'

### 3.	Build Fraud Ensemble Model

In [ ]:
param_grid1 = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 5, 10]
}

In [ ]:
model1, best_params1, results1 = run_random_forest_pipeline(
    X_train_1, X_test_1, y_train_1, y_test_1, param_grid1
)

### 4.	Cross-Validation

In [ ]:
results = run_stratified_kfold_pipeline(X1, y1, n_splits=5)